# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fuochi nella notte 2016 | Saltatempo
email: info@saltatempo.org
description: > # this means to ignore newlines until "baseurl:"
  XIV edizioine, 22-25 aprile 2016, Genazzano, Rock + Salsicce + Falò + Liberazione
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saltatempo.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
gems: ['jekyll-svg-plugin']
markdown: kramdown
sass:
  style: compressed
